FROM gcc:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake \
    libboost-all-dev \
    nlohmann-json3-dev \
    gdb \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY . ./backend

RUN mkdir -p backend/build && cd backend/build && \
    cmake .. && \
    make